---
- name: hello/vvsddsv
  hosts: "{{ tomcat_server_hosts }}"
  collections:
    - polaris.deploy
  vars_files:
    - "vars/standard/all.yaml"
    - "vars/standard/{{env_vars}}.yaml"
    - "vars/custom/all.yaml"
    - "vars/custom/{{env_vars}}.yaml"

  roles:
    # Establish the port number
    - name: port_manager

    # prepare the installation environment by creating the necessary folders
    - name: create_project_directories

    # create a self signed certificate to allow for HTTPS
    - name: self_signed_cert
      vars:
        ssc_format: "openssl"

    # install & configure the Tomcat container
    - name: nodejs
      vars:
        nodejs_version_number: "latest-v22.x"
        proxy_env: "{{ env_vars }}"

    - name: nodejs_app
      vars:
        proxy_env: "{{ env_vars }}"
